Changed OpenMP detection to AC_CHECK_LIB and WITH_OPENMP define.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -903,7 +903,8 @@ XML_LIBS
 xml2_config
 XML_DELEGATE_TRUE
 XML_DELEGATE_FALSE
-OPENMP_CXXFLAGS
+WITH_OPENMP_TRUE
+WITH_OPENMP_FALSE
 DX_PROJECT
 DX_CONFIG
 DX_DOCDIR
@@ -1565,7 +1566,6 @@ Optional Features:
                           ones [no]
   --disable-gsltest       Do not try to compile and run a test GSL program
   --disable-xmltest       Do not try to compile and run a test LIBXML program
-  --disable-openmp        do not use OpenMP
   --disable-doxygen-doc   don't generate any doxygen documentation
   --disable-doxygen-dot   don't generate graphics for doxygen documentation
   --enable-doxygen-man    generate doxygen manual pages
@@ -1590,6 +1590,7 @@ Optional Packages:
   --with-xml-prefix=PFX   Prefix where libxml is installed (optional)
   --with-xml-exec-prefix=PFX Exec prefix where libxml is installed (optional)
   --without-xml           disable XML support
+  --with-openmp           enable support for OpenMP parallelism
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -5092,13 +5093,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5095: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5096: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5098: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5099: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5101: output\"" >&5)
+  (eval echo "\"\$as_me:5102: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6209,7 +6210,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6212 "configure"' > conftest.$ac_ext
+  echo '#line 6213 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8535,11 +8536,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8538: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8539: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8542: \$? = $ac_status" >&5
+   echo "$as_me:8543: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8859,11 +8860,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8862: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8863: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8866: \$? = $ac_status" >&5
+   echo "$as_me:8867: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8964,11 +8965,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8967: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8968: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8971: \$? = $ac_status" >&5
+   echo "$as_me:8972: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9019,11 +9020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9022: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9026: \$? = $ac_status" >&5
+   echo "$as_me:9027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11767,7 +11768,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11770 "configure"
+#line 11771 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11867,7 +11868,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11870 "configure"
+#line 11871 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13870,11 +13871,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13873: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13874: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13877: \$? = $ac_status" >&5
+   echo "$as_me:13878: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13969,11 +13970,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13972: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13973: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13976: \$? = $ac_status" >&5
+   echo "$as_me:13977: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14021,11 +14022,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14024: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14025: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14028: \$? = $ac_status" >&5
+   echo "$as_me:14029: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16345,11 +16346,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16348: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16349: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16352: \$? = $ac_status" >&5
+   echo "$as_me:16353: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16444,11 +16445,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16447: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16448: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16451: \$? = $ac_status" >&5
+   echo "$as_me:16452: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16496,11 +16497,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16499: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16500: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16503: \$? = $ac_status" >&5
+   echo "$as_me:16504: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20493,26 +20494,38 @@ fi
 
 
 
-  OPENMP_CXXFLAGS=
-  # Check whether --enable-openmp was given.
-if test "${enable_openmp+set}" = set; then
-  enableval=$enable_openmp;
+# Check whether --with-openmp was given.
+if test "${with_openmp+set}" = set; then
+  withval=$with_openmp;
+else
+  with_openmp=yes
 fi
 
-  if test "$enable_openmp" != no; then
-    { echo "$as_me:$LINENO: checking for $CC option to support OpenMP" >&5
-echo $ECHO_N "checking for $CC option to support OpenMP... $ECHO_C" >&6; }
-if test "${ac_cv_prog_cxx_openmp+set}" = set; then
+if test "x$with_openmp" = xyes; then
+  # FIXME: Replace `main' with a function in `-lgomp':
+
+{ echo "$as_me:$LINENO: checking for main in -lgomp" >&5
+echo $ECHO_N "checking for main in -lgomp... $ECHO_C" >&6; }
+if test "${ac_cv_lib_gomp_main+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  cat >conftest.$ac_ext <<_ACEOF
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lgomp  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-#ifndef _OPENMP
- choke me
-#endif
-#include <omp.h>
-int main () { return omp_get_num_threads (); }
 
+int
+main ()
+{
+return main ();
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
 if { (ac_try="$ac_link"
@@ -20532,84 +20545,47 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_prog_cxx_openmp='none needed'
+  ac_cv_lib_gomp_main=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_prog_cxx_openmp='unsupported'
-	  	  	  	  	  	  	  	  	  	  	  	  	  for ac_option in -fopenmp -xopenmp -openmp -mp -omp -qsmp=omp; do
-	    ac_save_CXXFLAGS=$CXXFLAGS
-	    CXXFLAGS="$CXXFLAGS $ac_option"
-	    cat >conftest.$ac_ext <<_ACEOF
+	ac_cv_lib_gomp_main=no
+fi
 
-#ifndef _OPENMP
- choke me
-#endif
-#include <omp.h>
-int main () { return omp_get_num_threads (); }
-
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_gomp_main" >&5
+echo "${ECHO_T}$ac_cv_lib_gomp_main" >&6; }
+if test $ac_cv_lib_gomp_main = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBGOMP 1
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_cxx_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_prog_cxx_openmp=$ac_option
+
+  LIBS="-lgomp $LIBS"
+
 else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
+  if test "x$with_openmp" != xcheck; then
+			{ { echo "$as_me:$LINENO: error: --with-openmp was given, but test for openmp failed" >&5
+echo "$as_me: error: --with-openmp was given, but test for openmp failed" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
 
 fi
 
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-	    CXXFLAGS=$ac_save_CXXFLAGS
-	    if test "$ac_cv_prog_cxx_openmp" != unsupported; then
-	      break
-	    fi
-	  done
 fi
 
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_prog_cxx_openmp" >&5
-echo "${ECHO_T}$ac_cv_prog_cxx_openmp" >&6; }
-    case $ac_cv_prog_cxx_openmp in #(
-      "none needed" | unsupported)
-        ;; #(
-      *)
-        OPENMP_CXXFLAGS=$ac_cv_prog_cxx_openmp ;;
-    esac
-  fi
 
-
-if test -z "$OPENMP_CXXFLAGS" ; then
-  { echo "$as_me:$LINENO: WARNING: Could not detect OpenMP support." >&5
-echo "$as_me: WARNING: Could not detect OpenMP support." >&2;}
-  { echo "$as_me:$LINENO: If you have got multiple CPUs in your computer the speed of the program will drastically increase with OpenMP." >&5
-echo "$as_me: If you have got multiple CPUs in your computer the speed of the program will drastically increase with OpenMP." >&6;}
-  { echo "$as_me:$LINENO: Install a compiler with OpenMP support for better performance." >&5
-echo "$as_me: Install a compiler with OpenMP support for better performance." >&6;}
+ if test "x$with_openmp" = xyes; then
+  WITH_OPENMP_TRUE=
+  WITH_OPENMP_FALSE='#'
 else
-  { echo "$as_me:$LINENO: OpenMP support detected." >&5
-echo "$as_me: OpenMP support detected." >&6;}
+  WITH_OPENMP_TRUE='#'
+  WITH_OPENMP_FALSE=
 fi
+
 
 ######################################################################
 # DOXYGEN SUPPORT
@@ -23744,6 +23720,13 @@ echo "$as_me: error: conditional \"XML_DELEGATE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${WITH_OPENMP_TRUE}" && test -z "${WITH_OPENMP_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_OPENMP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_OPENMP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${DX_COND_doc_TRUE}" && test -z "${DX_COND_doc_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"DX_COND_doc\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -25047,7 +25030,8 @@ XML_LIBS!$XML_LIBS$ac_delim
 xml2_config!$xml2_config$ac_delim
 XML_DELEGATE_TRUE!$XML_DELEGATE_TRUE$ac_delim
 XML_DELEGATE_FALSE!$XML_DELEGATE_FALSE$ac_delim
-OPENMP_CXXFLAGS!$OPENMP_CXXFLAGS$ac_delim
+WITH_OPENMP_TRUE!$WITH_OPENMP_TRUE$ac_delim
+WITH_OPENMP_FALSE!$WITH_OPENMP_FALSE$ac_delim
 DX_PROJECT!$DX_PROJECT$ac_delim
 DX_CONFIG!$DX_CONFIG$ac_delim
 DX_DOCDIR!$DX_DOCDIR$ac_delim
@@ -25098,7 +25082,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 91; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 92; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
